# Generated by Django 3.2.2 on 2023-07-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reddituser',
            name='display_picture',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='reddituser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
